# Site settings
title: Jollie Tree
email: jollietree@aol.com
tel: 608-206-2834
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jollietree.com" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
permalink: pretty

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
